### ISSUE TITLE
Specify minimum lein version

### ISSUE THREAD

**Issue by jstoneham** [pliant/lein-package#5]
I spent a couple hours working through an issue today where the install hook wouldn't install anything. Turns out the code in install.clj (and presumably deploy.clj) makes calls to pomegranate (aether/install-artifacts :files files) where the older versions of pomegranate (e.g., 0.0.13) require an :artifacts key as well. I was using lein 2.0.0-preview10.

Upgrading to lein 2.1.2 fixed the issue. It uses pomegranate 0.2.0. It would be nice to specify the minimum lein version.

**Comment by dfrugg** [comment]
Thanks for the input.  Lein version compatibility is a topic that is being fleshed out.  The current target is 2.0, but I have pull requests that add value but are targetted for 2.1+.  I plan to have this figured out within the week.
